FROM ubuntu:latest

RUN apt-get update && \
    curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash - \
    sudo apt install -y nodejs
    sudo apt install -y nginx

FROM node:16-alpine as build

WORKDIR /app

COPY package*.json ./

RUN npm install
    npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]